---
title: "hw5"
author: "Stephen Powers"
date: "11/8/2019"
output: github_document
---

## Problem 1 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(viridis)
library(patchwork)
```


```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

```{r}
fill_missing = function(x) {
  if (is.numeric(x)) 
    {replace_na(x, mean(x, na.rm = TRUE))} 
  else if (is.character(x)) 
    {replace_na(x, "virginica")}}

iris_fill = map_df(iris_with_missing, fill_missing)
```

## Problem 2 

```{r}
p2_data = 
  list.files("./data/", pattern = ".csv", full.names = TRUE) %>% view
```

```{r}
p2_tidy_data = 
  p2_data %>% map_df(read.csv) %>% 
  mutate(id = tools::file_path_sans_ext(basename(p2_data))) %>% 
  separate(id, into = c("group", "id_number"), sep = "_") %>% 
  mutate(group = recode(group, "con" = "control", "exp" = "experimental")) %>% 
  select(group, id_number, everything()) %>% 
  pivot_longer(week_1:week_8,
    names_to = "week",
    values_to = "value",
    names_prefix = "week_") %>% view
```


## Problem 3 



